#!/bin/bash
#
# generate a  Cookbook 2 subduction type model, van Keken et al. benchmark
#
#
sub_types=${1-"A B C"}			# A, B, or C type benchmark
dx=${2-10}			# resolution in km (out of 660x600km)
viscE=${3-0}			# exp(E(T-T0)) type visc dependent viscosity
plate_age=${4-50}		# plate age in Myr


make				# for erf function

for sub_type in $sub_types;do
    
    name=tests.$sub_type.$dx.$viscE.$plate_age

    # from benchmark
    #geom="-v width=660 -v height=600"
    # bigger
    geom="-v width=1000 -v height=800"
    opt="-v dx=$dx -v sub_type=$sub_type -v viscosityE=$viscE  -v plate_age=$plate_age $geom"
    
    gawk $opt                 -f make_conman_subduction_in.awk > in.$name
    gawk $opt -v print_geom=1 -f make_conman_subduction_in.awk > geom.$name
    
    cat <<EOF > run.$name
in.$name      
geom.$name
out.$name
r.in
r.$name
tser.$name
temp.$name
stress.$name
comp.$name
geoid.$name
EOF
    echo $0: running $name test
    echo
    ../conman < run.$name
    echo 
    echo $0: plotting
    echo 
    plot_simple_slab $name
done

